---
- hosts: all
  become: yes
  roles:
    - ansible-role-postgresql
    - ansible-role-docker
  tasks:
    - name: setup root key
      authorized_key:
        user: root
        key: "{{ lookup('file', item) }}"
        state: present
        exclusive: True
      with_fileglob:
        - public_keys/*.pub
    - name: Add the user vagrant to the docker group
      user:
        name: vagrant
        groups: docker
        append: yes
